---
title: "subset-polar-data-with-shapefile"
author: "Sunny Hospital"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Function to check if pkgs are installed, install missing pkgs, and load
pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dep=TRUE,repos='http://cran.us.r-project.org')
    if(!require(x,character.only = TRUE)) stop(x, " :Package not found")
  }
}

list.of.packages <- c("sp", "ggplot2" ,"ncdf4",  "RColorBrewer", "scales", "reshape2")

# create list of installed packages
pkges = installed.packages()[,"Package"]
for (pk in list.of.packages) {
  pkgTest(pk)
}
```

### The tutorial demonstrates the following techniques
* Download sea ice satellite data from the PolarWatch ERDDAP data server
* Import geographical features of Lake Iliamna from a shapefile
* Transform data from one projection to another
* Subset the satellite data for Lake Iliamna
* Visualize data in different projection


```{r}
library(terra)
library(sf)
library(ggplot2)
library(rerddap)

```

```{r read_shapefile}
# Set directory path for shapefile
dir_path <- '../resources/World_Lakes_shapes/World_Lakes.shp'


# Load the shape file
shapes <- st_read(dsn = dir_path)

# View
print(shapes)
# Example List of all the province names


# Get boundary coordinates for Lake Iliamna
lake <- shapes[shapes$Lake_name == "Iliamna", ]
head(lake)
ggplot(data = lake) +
  geom_sf() +
  theme_minimal() +
  labs(title = "Lake Iliamna", 
       caption = "Source: shapefile")
nrow(shapes)


```



```{r erddap_data}

pw_url = "https://polarwatch.noaa.gov/erddap/"
dataset_id = "usnic_ims_4km"
var_name = "IMS_Surface_Values"
dat_info <- info(datasetid = dataset_id, url = pw_url)
dat_info


dat <- griddap(dat_info,  time = c('2019-11-01','2019-11-01'), fields = var_name)

```

```{r}
ims <- dat$data

```


```{r}
# Visualize the data (warning: this takes awhile to )
ggplot(data = ims, aes(x = x, y = y, fill=IMS_Surface_Values)) +
         geom_tile() + 
         coord_fixed(ratio = 1) + 
         scale_y_continuous() + 
         scale_x_continuous() +
         scale_fill_gradientn(colours=rev(brewer.pal(n = 3, name = "Blues")),na.value="tan") +
         ggtitle("IMS Data")
```

## Check CRS of Lake data

```{r}

#proj4string(polarB) <-CRS("+init=epsg:4326")

st_crs(lake_shp)
shapes_polar <- spTransform(shapes, CRS("+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-80 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6356257 +units=m +no_defs"))

crs <- CRS("+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-80 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6356257 +units=m +no_defs")
shapes_transformed <- st_transform(lake, crs)
ggplot(data = shapes_transformed) +
  geom_sf() +
  theme_minimal() +
  labs(title = "Lake Iliamna in Polar stereographic projection", 
       caption = "Source: shapefile")

```



